# pnpm configuration, see https://pnpm.io/settings

# Minimum age for a package release to be considered valid (in minutes).
minimumReleaseAge: 4320 # 3 days

# Allowed scripts
allowBuilds:
  esbuild: true
  msw: true
  spawn-sync: true
