name: Release

# Use a concurrency group to avoid releasing the same version multiple times in parallel
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel the previous job

on:
  # When a version tag is pushed
  push:
    tags:
      - "v*"

permissions:
  contents: write # To clone the repository and create the release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install the dependencies
        run: pnpm install --frozen-lockfile

      - name: Check the format
        run: pnpm run format

      - name: Lint the code
        run: pnpm run lint

      - name: Check the types
        run: pnpm run typecheck

      - name: Run the tests
        run: pnpm run test

      - name: Build the extension (Chrome)
        run: pnpm run build

      - name: Build the extension (Firefox)
        run: pnpm run build:firefox

      - name: Package the extension (Chrome)
        run: pnpm run zip

      - name: Package the extension (Firefox)
        run: pnpm run zip:firefox

      - name: Create the release
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/atlassian-forge-devtools-*.zip
