name: Release
run-name: Release ${{ inputs.dry-run == true && '(dry run)' || '' }}

# Use a concurrency group to avoid releasing multiple versions at the same time
concurrency:
  group: release
  cancel-in-progress: false # Don't cancel a pending release

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Perform a dry run
        required: false
        type: boolean
        default: false

permissions:
  contents: read # To clone the repository

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required to analyze commits since the last release
          persist-credentials: false # To avoid interfering with the custom GitHub App token

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install the dependencies
        run: pnpm install --frozen-lockfile

      - name: Check the format
        run: pnpm run format

      - name: Lint the code
        run: pnpm run lint

      - name: Check the types
        run: pnpm run typecheck

      - name: Run the tests
        run: pnpm run test

      - name: Build the extension (Chrome)
        run: pnpm run build

      - name: Build the extension (Firefox)
        run: pnpm run build:firefox

      - name: Release the extension
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: "${{ vars.RELEASE_BOT_APP_NAME }}[bot]"
          GIT_AUTHOR_EMAIL: "${{ vars.RELEASE_BOT_USER_ID }}+${{ vars.RELEASE_BOT_APP_NAME }}[bot]@users.noreply.github.com"
          GIT_COMMITTER_NAME: "${{ vars.RELEASE_BOT_APP_NAME }}[bot]"
          GIT_COMMITTER_EMAIL: "${{ vars.RELEASE_BOT_USER_ID }}+${{ vars.RELEASE_BOT_APP_NAME }}[bot]@users.noreply.github.com"
        run: pnpm exec semantic-release ${{ inputs.dry-run == true && '--dry-run' || '' }}

      - name: Submit the extension
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
        run: |
          pnpm run submit --dry-run \
            --chrome-zip dist/*-chrome.zip \
            --firefox-zip dist/*-firefox.zip --firefox-sources-zip dist/*-sources.zip
